version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    allow:
      - dependency-name: "@dcl/*"
      - dependency-name: "dcl-*"
      - dependency-name: "decentraland*"
    versioning-strategy: increase
    open-pull-requests-limit: 10
