version: "1.0"
services:
  kernel:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./init.sh:/init.sh
    entrypoint: sh -c "/init.sh"
    ports:
      - 7666:7666
      - 8080:8080
