export enum PermissionItem {
  ALLOW_TO_MOVE_PLAYER_INSIDE_SCENE = 'ALLOW_TO_MOVE_PLAYER_INSIDE_SCENE',
  ALLOW_TO_TRIGGER_AVATAR_EMOTE = 'ALLOW_TO_TRIGGER_AVATAR_EMOTE',
  USE_WEB3_API = 'USE_WEB3_API',
  USE_WEBSOCKET = 'USE_WEBSOCKET',
  USE_FETCH = 'USE_FETCH'
}
