on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - created

name: test-build-deploy
jobs:
  validations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: browser-actions/setup-chrome@latest

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
      - name: install

        run: |
          sudo apt-get install xvfb
          npm ci
          make install_protoc

      - name: generate protocol code
        run: make compile_apis

      - name: test-ci
        run: xvfb-run --auto-servernum make test-ci

      - name: lint
        run: make lint

      # - name: codecov

      #   run: npx codecov
  build:
    runs-on: ubuntu-latest
    outputs:
      dcl_kernel_s3_bucket_key: ${{ steps.publish_dcl_kernel.outputs.s3-bucket-key }}
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Get the current branch name
        shell: bash
        run: node -e "console.log('::set-output name=branch::' +    ('${{github.head_ref}}' || '$GITHUB_REF'.replace('refs/heads/',''))    )"
        id: myref

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'

      - name: set package.json version
        uses: menduz/oddish-action@master
        with:
          deterministic-snapshot: true
          only-update-versions: true
          cwd: ./static

      - name: install
        run: npm ci

      - name: build
        run: make build-essentials build-release build-deploy
      - uses: hmarr/debug-action@v2
      - name: publish packages
        uses: menduz/oddish-action@master
        id: publish_dcl_kernel
        with:
          registry-url: 'https://registry.npmjs.org'
          access: public
          cwd: ./static
          ## use action runId instead of current date to generate snapshot numbers
          deterministic-snapshot: true

          ## publish every package to s3
          s3-bucket: ${{ secrets.SDK_TEAM_S3_BUCKET }}
          s3-bucket-key-prefix: '@dcl/kernel/branch/${{ steps.myref.outputs.branch }}'

          ## inform gitlab after publishing to proceed with CDN propagation
          gitlab-token: ${{ secrets.GITLAB_TOKEN }}
          gitlab-pipeline-url: ${{ secrets.GITLAB_URL }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.SDK_TEAM_AWS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SDK_TEAM_AWS_SECRET }}

      - name: deploy preview
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.SDK_TEAM_AWS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SDK_TEAM_AWS_SECRET }}
          CDN_BUCKET: ${{ secrets.SDK_TEAM_S3_BUCKET }}
        run: |
          npx @dcl/cdn-uploader@next \
            --bucket $CDN_BUCKET \
            --local-folder static \
            --bucket-folder "@dcl/kernel/branch/${{ steps.myref.outputs.branch }}"

  notify_deployment:
    needs: [build]
    if: ${{ github.event.pull_request.number }}
    runs-on: ubuntu-latest
    name: Deployment Notification
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Test this pull request

      - name: Get the current branch name
        shell: bash
        run: node -e "console.log('::set-output name=branch::' +    ('${{github.head_ref}}' || '$GITHUB_REF'.replace('refs/heads/',''))    )"
        id: myref

      - name: Generate S3 URL
        id: url-generator
        run: |
          body=$(echo ${{ secrets.SDK_TEAM_S3_BASE_URL }})/${{ needs.build.outputs.dcl_kernel_s3_bucket_key }}
          echo ::set-output name=body::$body

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            # Test this pull request
            - This branch can be previewed at https://play.decentraland.zone/?kernel-branch=${{ steps.myref.outputs.branch }}
            - The `@dcl/kernel` package can be tested in scenes by running
               ```bash
               npm install "${{ steps.url-generator.outputs.body }}"
               ```
          edit-mode: replace
